// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUaM2EjSNrs2O_UgQ40m-oEQHmmv0oIhg',
    appId: '1:166944444888:web:bef233323693ecc85722ad',
    messagingSenderId: '166944444888',
    projectId: 'bloodbank-ba7bd',
    authDomain: 'bloodbank-ba7bd.firebaseapp.com',
    storageBucket: 'bloodbank-ba7bd.appspot.com',
    measurementId: 'G-PV8PZY8J19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqsxEVZ_yx6jgJLGRGnBvIjPGBb_tpbas',
    appId: '1:166944444888:android:3fef5531862e5faa5722ad',
    messagingSenderId: '166944444888',
    projectId: 'bloodbank-ba7bd',
    storageBucket: 'bloodbank-ba7bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0IRw7vi3iJHKZEyNAagWjSAWgzS2YcU',
    appId: '1:166944444888:ios:3f06305a15d09f1c5722ad',
    messagingSenderId: '166944444888',
    projectId: 'bloodbank-ba7bd',
    storageBucket: 'bloodbank-ba7bd.appspot.com',
    iosClientId: '166944444888-pkmqp9otm07oses4g46k6h9346t7g11d.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0IRw7vi3iJHKZEyNAagWjSAWgzS2YcU',
    appId: '1:166944444888:ios:3f06305a15d09f1c5722ad',
    messagingSenderId: '166944444888',
    projectId: 'bloodbank-ba7bd',
    storageBucket: 'bloodbank-ba7bd.appspot.com',
    iosClientId: '166944444888-pkmqp9otm07oses4g46k6h9346t7g11d.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank',
  );
}
